### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by sunmd01** [adoyle-h/one.nvim#1]
![image](https://user-images.githubusercontent.com/9304859/201563730-49c82ca7-b0b3-4213-b161-76c0357b3a8b.png)

**Comment by adoyle-h** [comment]
按下 `:Notifications` 看完整的错误信息。notify 窗口没有换行，错误信息显示不完整。

**Comment by adoyle-h** [comment]
已复现问题，table.unpack 为 nil 导致的。更新最新代码，应该修复了。

**Comment by sunmd01** [comment]
> 已复现问题，table.unpack 为 nil 导致的。更新最新代码，应该修复了。

好的多谢
