### ISSUE TITLE
Errors when launch: luaformatter: failed to install

### ISSUE THREAD

**Issue by pluveto** [adoyle-h/one.nvim#10]
```
2023-01-30T12:06:47  INFO [mason-tool-installer] luaformatter: installing
2023-01-30T12:06:47  ERROR [mason-tool-installer] luaformatter: failed to install
```

This can be fixed by `brew install luarocks`, should be placed into the documentation?

**Comment by adoyle-h** [comment]
Thanks. I added it to FAQ. See this commit https://github.com/adoyle-h/one.nvim/commit/70e3049589d66a5ace87a3d6dc00e28cbd70ea15

**Comment by osjason** [comment]
在 ubuntu 22.04 尝试安装 one.nvim 插件，并顺手执行了一下 `nvim .bashrc`，一开始是进入 nvim 直接报错
```
Error detected while processing BufReadPost Autocommands for "*":
E5108: Error executing lua vim/_editor.lua:0: BufReadPost Autocommands for "*"..script nvim_exec2() called at BufReadPost Autocommands for "*":0: Vim(call)
:E117: Unknown function: dist#ft#SetFileTypeSH
stack traceback:
        [C]: in function 'nvim_exec2'
        vim/_editor.lua: in function 'cmd'
        ...plugins/filetype.nvim/lua/filetype/mappings/function.lua:480: in function 'name'
        ...l/share/nvim/plugins/filetype.nvim/lua/filetype/init.lua:17: in function 'set_filetype'
        ...l/share/nvim/plugins/filetype.nvim/lua/filetype/init.lua:65: in function 'try_lookup'
        ...l/share/nvim/plugins/filetype.nvim/lua/filetype/init.lua:171: in function 'resolve'
        [string ":lua"]:1: in main chunk
```
随后，mason-tool-installer 报错：
```shell
2023-06-08T19:52:06  INFO [mason-tool-installer] luaformatter: installing
2023-06-08T19:52:10  INFO [mason-tool-installer] lua-language-server: successfully installed
2023-06-08T19:52:39  ERROR [mason-tool-installer] luaformatter: failed to install
```
依赖版本：
```shell
lua -v
# Lua 5.3.5  Copyright (C) 1994-2018 Lua.org, PUC-Rio

luarocks --version
# /usr/local/bin/luarocks 3.8.0       
# LuaRocks main command-line interface

nvim -v
# NVIM v0.9.1        
# Build type: Release
# LuaJIT 2.1.0-beta3
#   system vimrc file: "$VIM/sysinit.vim"
#  fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"
# Run :checkhealth for more info

python --version
# Python 3.10.10

pip3 --version
# pip 23.0.1 from /home/jasonos/miniconda3/lib/python3.10/site-packages/pip (python 3.10)

pip3 show pynvim
# Name: pynvim
# Version: 0.4.3
# Summary: Python client to neovim
# Home-page: http://github.com/neovim/pynvim
# Author: Thiago de Arruda
# Author-email: tpadilha84@gmail.com
# License: Apache
# Location: /home/jasonos/miniconda3/lib/python3.10/site-packages
# Requires: greenlet, msgpack
# Required-by:

apt show ripgrep
# ...
# Version: 13.0.0-2ubuntu0.1
# Built-Using: rustc (= 1.59.0+dfsg1-1~ubuntu2~22.04.1)
# ...

gcc --version
# gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0

dpkg -l | grep libstdc++
# libstdc++-11-dev:amd64  11.3.0-1ubuntu1~22.04.1 amd64 GNU Standard C++ Library v3 (development files)
# libstdc++6:amd64  12.1.0-2ubuntu1~22.04    amd64    GNU Standard C++ Library v3
```

**Comment by osjason** [comment]
> 在 ubuntu 22.04 尝试安装 one.nvim 插件，并顺手执行了一下 `nvim .bashrc`，一开始是进入 nvim 直接报错
> 
> ```
> Error detected while processing BufReadPost Autocommands for "*":
> E5108: Error executing lua vim/_editor.lua:0: BufReadPost Autocommands for "*"..script nvim_exec2() called at BufReadPost Autocommands for "*":0: Vim(call)
> :E117: Unknown function: dist#ft#SetFileTypeSH
> stack traceback:
>         [C]: in function 'nvim_exec2'
>         vim/_editor.lua: in function 'cmd'
>         ...plugins/filetype.nvim/lua/filetype/mappings/function.lua:480: in function 'name'
>         ...l/share/nvim/plugins/filetype.nvim/lua/filetype/init.lua:17: in function 'set_filetype'
>         ...l/share/nvim/plugins/filetype.nvim/lua/filetype/init.lua:65: in function 'try_lookup'
>         ...l/share/nvim/plugins/filetype.nvim/lua/filetype/init.lua:171: in function 'resolve'
>         [string ":lua"]:1: in main chunk
> ```
> 
> 随后，mason-tool-installer 报错：
> 
> ```shell
> 2023-06-08T19:52:06  INFO [mason-tool-installer] luaformatter: installing
> 2023-06-08T19:52:10  INFO [mason-tool-installer] lua-language-server: successfully installed
> 2023-06-08T19:52:39  ERROR [mason-tool-installer] luaformatter: failed to install
> ```
> 
> 依赖版本：
> 
> ```shell
> lua -v
> # Lua 5.3.5  Copyright (C) 1994-2018 Lua.org, PUC-Rio
> 
> luarocks --version
> # /usr/local/bin/luarocks 3.8.0       
> # LuaRocks main command-line interface
> 
> nvim -v
> # NVIM v0.9.1        
> # Build type: Release
> # LuaJIT 2.1.0-beta3
> #   system vimrc file: "$VIM/sysinit.vim"
> #  fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"
> # Run :checkhealth for more info
> 
> python --version
> # Python 3.10.10
> 
> pip3 --version
> # pip 23.0.1 from /home/jasonos/miniconda3/lib/python3.10/site-packages/pip (python 3.10)
> 
> pip3 show pynvim
> # Name: pynvim
> # Version: 0.4.3
> # Summary: Python client to neovim
> # Home-page: http://github.com/neovim/pynvim
> # Author: Thiago de Arruda
> # Author-email: tpadilha84@gmail.com
> # License: Apache
> # Location: /home/jasonos/miniconda3/lib/python3.10/site-packages
> # Requires: greenlet, msgpack
> # Required-by:
> 
> apt show ripgrep
> # ...
> # Version: 13.0.0-2ubuntu0.1
> # Built-Using: rustc (= 1.59.0+dfsg1-1~ubuntu2~22.04.1)
> # ...
> 
> gcc --version
> # gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
> 
> dpkg -l | grep libstdc++
> # libstdc++-11-dev:amd64  11.3.0-1ubuntu1~22.04.1 amd64 GNU Standard C++ Library v3 (development files)
> # libstdc++6:amd64  12.1.0-2ubuntu1~22.04    amd64    GNU Standard C++ Library v3
> ```

同时，在 nvim 中运行指令 `:MasonLog`，得到
```
8 [INFO  2023年06月08日 星期四 20时45分25秒] ...vim/plugins/mason.nvim/lua/mason-core/installer/init.lua:184: Executing installer for Package(name=luafor
    ↪matter) {}
  9 [ERROR 2023年06月08日 星期四 20时45分59秒] ...vim/plugins/mason.nvim/lua/mason-core/installer/init.lua:249: Installation failed for Package(name=luafor
    ↪matter) error=spawn: luarocks failed with exit code 1 and signal 0. 
```
