### ISSUE TITLE
Mouse copy looks not work

### ISSUE THREAD

**Issue by x2c3z4** [adoyle-h/one.nvim#16]
Select texts with mouse, and Command-C to copy, nothing is copied.

**Comment by adoyle-h** [comment]
I think it is not a usual cases in vim. And I tried `<D-c>` and `<cmd>c`, neither works.
How do you bind Command-C in vim?

**Comment by x2c3z4** [comment]
I don't create keymaps with ⌘, and I also use iTerm2 to ssh to remote server, <leader> y works well, so this solution is acceptable.

Millions of thanks.
