### ISSUE TITLE
Add tokyonight themes

### ISSUE THREAD

**Issue by x2c3z4** [adoyle-h/one.nvim#2]
The default theme looks not so good, tokyonight is more beautiful.

**Comment by adoyle-h** [comment]
It is hard to define a "good" for everyone. Everyone has their own preferences. So it also hard to make a default theme looks good to everyone.

You can disable the default theme and enable `tokyonight` in your `init.lua`. For example,

```lua
require('one').setup {
	plugins = {
		{ 'onedarkpro', disable = true },

		{
			'folke/tokyonight.nvim',

			config = function(config)
				local conf = config.tokyonight
				vim.cmd('colorscheme ' .. conf.colorscheme)
				require('tokyonight').setup(conf.setup)
			end,

			defaultConfig = {
				'tokyonight',
				{
					colorscheme = 'tokyonight', -- https://github.com/folke/tokyonight.nvim#-usage
					setup = {}, -- https://github.com/folke/tokyonight.nvim#%EF%B8%8F-configuration
				},
			},
		},
	},
}
```

Some places do not look good,  that you need to solve them by yourself.
Please read the [Colors and Highlights](https://github.com/adoyle-h/one.nvim/blob/master/doc/colors.md). You may need to change the [config.colors](https://github.com/adoyle-h/one.nvim/blob/master/doc/lua/one/config/colors.lua) and [colors/highlights](https://github.com/adoyle-h/one.nvim/blob/master/doc/lua/one/plugins/colors/highlights.lua) and [the highlights for plugins](https://github.com/adoyle-h/one.nvim/blob/master/doc/colors.md#the-highlights-for-plugins).

**Comment by adoyle-h** [comment]
It's not a bug. Please open a [discussion](https://github.com/adoyle-h/one.nvim/discussions) for question and suggestion. Github issue only for bug report. Please read [Suggestion, Bug Reporting, Contributing](https://github.com/adoyle-h/one.nvim#suggestion-bug-reporting-contributing).
