### ISSUE TITLE
安装

### ISSUE THREAD

**Issue by LEON-gittech** [adoyle-h/one.nvim#21]
看了半天我还是不太懂你这个是怎么用的，如果直接在 init.lua 中 require（one）的话会警告找不到该模块，根据你的文档是 git clone 到/Users/macbook/.local/share/nvim/site/pack/user/start/one.vim，那按照 lua 的语法确实导入不了呀，而且也不在他寻找的一些备用路径里。

同时，如果按照 包管理器Lazy的包导入方式，导入是可以导入了，但什么效果都没有。

还是请你给出一个易于理解的使用方式谢谢。

**Comment by LEON-gittech** [comment]
搞好了，我的问题，，，，，，需要在 init.lua 中禁用掉 require(lazy)，否则one 就不会生效。搞了一晚上，有点搞心态属于是。

**Comment by adoyle-h** [comment]
严格按照文档步骤来就肯定没问题。
https://github.com/adoyle-h/one.nvim/blob/master/doc/install-and-init.zh.md#%E5%88%9D%E5%A7%8B%E5%8C%96
