### ISSUE TITLE
'dw' delete word should only delete word

### ISSUE THREAD

**Issue by x2c3z4** [adoyle-h/one.nvim#3]
'dw' will delete the following punctuation marks(e.g. ';') and ('\n'), how to fix?

**Comment by adoyle-h** [comment]
You should use `de`. `dw` works as expected, see `:h motion`.

**Comment by adoyle-h** [comment]
It's not a bug. Please open a [discussion](https://github.com/adoyle-h/one.nvim/discussions) for question. Github issue only for bug report.
